# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel_info"
batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128
optimizer: 'adam'

t_max: 10000000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "info_mac"
agent: "qgnn"
agent_output_type: q

learner: "nq_learner"
mixer: "qgnn"
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
q_lambda: False

# options
model_gnn_type: "edgeconv"
model_gnn_layers: 2
model_use_layernorm: True
model_adj_dropout: 0.0

mixer_use_genagg: True
mixer_use_batchnorm: False
mixer_use_hypernet: False
mixer_hypernet_flat: False
mixer_heterogeneous: False
mixer_embed_dim: 8
mixer_psi_layers: 2
mixer_phi_layers: 2
mixer_midmult: 2.0

# Priority experience replay
use_per: False
per_alpha: 0.6
per_beta: 0.4
return_priority: False

name: "qgnn_env=8_adam_td_lambda"

# QMIX params
mixing_embed_dim: 32
hypernet_embed: 64