
env: estimate

env_args:
  map_name: "estimate"
  n_agents: 8
  n_actions: 10

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
