
env: set

env_args:
  map_name: "set"
  n_agents: 16
  n_actions: 4
  batch_size: null

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000

obs_agent_id: False
obs_last_action: False
rnn_hidden_dim: 8
